name: Deploy to Render

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 🔹 Backend (Go) Docker Build and Push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -f Dockerfile -t darkfat123/golang-ws:latest .
          docker push darkfat123/golang-ws:latest

      # 🔹 Deploy Backend to Render
      - name: Trigger Backend Deploy
        run: curl -X POST "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_UAT_URL }}"

      # 🔹 Frontend (Vue.js) Build and Deploy
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies and build Vue app
        run: |
          cd web-vue
          npm install
          npm run build

      # 🔹 Deploy Frontend to Render
      - name: Trigger Frontend Deploy
        run: curl -X POST "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_UAT_URL }}"
